xwiki:
  image: lavadiablo/docker-xwiki:latest
  links:
   - xwikidb
  ports:
   - "8082:8080"
  volumes:
   - /usr/share/docker/persistance/xwiki/files:/var/local/xwiki
xwikidb:
  image: postgres
  volumes:
   - /usr/share/docker/persistance/xwiki/db:/var/lib/postgresql/data
  environment:
   - POSTGRES_USER=xwiki
   - POSTGRES_PASSWORD=xwiki
